martinakaduc/MM241-Assignment

student_submissions/s2310737_2311628_2311659_2312130_2313200/algor.py, student_submissions/s2310737_2311628_2311659_2312130_2313200/policy2310737_2311628_2311659_2312130_2313200.py
This submission consists of 2 algorithms: Column generation and Worst Fit.
- `s2310737_2311628_2311659_2312130_2313200/algor.py`: contains the 2 algorithms
- `s2310737_2311628_2311659_2312130_2313200/policy2310737_2311628_2311659_2312130_2313200.py`: contains the Policy class for choosing between those two algorithms.
| | Column generation | Worst fit|
|--|------|--|
| Run time (seconds) | 58.67 | 41.49 |
| Average trim loss | 0.247 | 0.179 |
| Average fill rate (1 - trim_loss) | 0.753 | 0.821 |
=> Submission for group 2310737, 2311628, 2311659, 2312130 and 2313200

student_submissions/s2310270/policy2310270.py, student_submissions/s2310270_2310779_2310348_2314057_2310655/policy2310270_2310779_2310348_2314057_2310655.py
**Team 148: Implement Branch and Price Policy and First Fit Decreasing Policy for solving the 2D Cutting Stock Problem.** 
In this pull request, our team has implemented two algorithms to solve the 2D Cutting Stock Problem: **Branch and Price algorithm** and **First Fit Decreasing algorithm**.
- Branch and Price is a method that combines two powerful algorithms: Branch and Bound and Column Generation. This algorithm is often used to solve large combinatorial optimization problems with complex search spaces and many variables, such as the 2D Cutting Stock Problem. Column Generation helps solve subproblems in each branch by generating new columns to improve the solution. Branch and Bound divides the search space into branches and eliminates branches that are unlikely to lead to better …
=> submission 2310270_2310779_2310348_2314057_2310655

student_submissions/s2210xxx/policy2210xxx.py, student_submissions/s2353269_2353235_2252723_2352689_2352608/policy2353269_2353235_2252723_2352689_2352608.py, student_submissions/s2353269_2353235_2252723_2352689_2352608/requirements.txt
1. Student ID: 2353269 - 2252723 
2. Brief descriptions:
-  Policy 1: Corner-First Optimization
Policy 1 prioritizes placing items in corners, then edges, to maximize space utilization and packing density. Using a scoring system, it evaluates positions based on proximity to edges and corners, as well as neighboring items, while allowing rotation for better fit. Larger or harder-to-place items are handled first, ensuring efficient use of space. This heuristic is fast and effective but focuses on localized optimization.
-  Policy 2: 
The implemented solution combines several powerful heuristic strategies to tackle the 2D bin packing problem efficiently. At its core, it employs a Largest-First Best-Fit heuristic that prioritizes placing larger items first to minimize space fragmentation. …
=> Group_52_Instructor_Tran_Hong_Tai(2353269 - 2353235 - 2252723 - 2352689 - 2352608)

student_submissions/s2312562_2213826_2213960_2213416/Policy2312562_2213826_2213960_2213416.py
My team implemented two algorithms for solving the 2D cutting stocks problem: **First Fit Decreasing** and **Genetic Algorithm**.
**First Fit Decreasing:**
- Sort the list of products in descending order by their area.
- Place products in the sorted list sequentially if they fit the first available position in the current stock (products may be rotated).
**Genetic Algorithm:**
- An individual in the biome represents the placement of all products.
- The biome evolves through generations to enhance the fitness of individuals, focusing on reducing waste and maximizing area utilization.
Based on the dataset used for testing and comparing results with the provided Random and Greedy algorithms, the performance metrics are summarized in the following table:
| Algorithm               | Runtime …
=> Submission (Group 125) 2312562_2213826_2213960_2213416

student_submissions/s2313962_2313966_2310207_2312371_2311145/policy2313962_2313966_2310207_2312371_2311145.py
The **Improved Priority Heuristic** algorithm applies a divide-and-conquer strategy to solve the problem. Specifically, after a product is cut from the material stock, the remaining part of the stock is divided into two smaller pieces. The entire stock is recursively cut by maximizing the cuts on the newly created pieces.
The **Greedy Scoring** algorithm employs a greedy method, where each product is selected and placed in the best position based on a scoring function.
The scoring function is determined by factors such as:
- Optimizing the usage of space in the material stock.
- Minimizing the distance from the origin (prioritizing positions near the top-left corner).
- Enhancing the adjacency of filled cells.
- Avoiding unnecessary use of new material stock.
---
- Nguyễn Tăng Vũ - …
=> Submission 2313962_2313966_2310207_2312371_2311145_Group103

student_submissions/s2352276_2352418_2352440_2353339_2352410/policy2352276_2352418_2352440_2353339_2352410.py
**First-Fit Decreasing (FFD):**
Sorts products in decreasing order of size and places each product into the first stock that can accommodate it. This method prioritizes filling larger spaces first to maximize space utilization.
**Quick Learning:**
Dynamically optimize product placement. It iteratively generates potential placement columns and employs learning mechanisms to predict the most efficient placements based on historical data and patterns.
**FFD**
The implementation of the FFD policy begins by sorting products and stocks in descending order based on their area (width × height) to prioritize larger items. Each product is then placed in the first stock that can accommodate it without rotation, effectively minimizing the number of stocks required through efficient packing.
**Quick …
=> Submission_2352276_2352418_2352440_2353339_2352410

student_submissions/s2352288_2352910_2352761_2353114_2252048/policy2352288_2352910_2352761_2353114_2252048.py
This is the submisson code of group 30 for the MM241 Assignment. In this submission we implement 2 policy based on Albano-Sapuppo Algorithm and Genetic Algorithm, all are heuristics approach.
=> Submission of Group 30_2352288_2352910_2352761_2353114_2252048

student_submissions/s2352696_2353341_2353027_2352300_2352112/policy2352696_2353341_2353027_2352300_2352112.py, student_submissions/s2352696_2353341_2353027_2352300_2352112/requirements.txt
1. Nguyễn Vũ Long                          ID : 2352696
2. Lê Phước Vũ                                 ID : 2353341
3. Nguyễn Hoàng Quốc                   ID : 2353027
4. Trương Trí Hào                             ID :  2352300
5. Trịnh Vũ Thiên Bảo                       ID : 2352112
**Column Generation** is an advanced optimization approach for large-scale **Linear Programming (LP)** problems. It works by **iteratively generating and adding variables** (or "columns") to the *Restricted Master Problem* (RMP).  
**How it Works**
1. Start with a **Restricted Master Problem (RMP)** that contains a limited subset of variables (columns).  
7. **Iteratively solve** the RMP and identify promising new variables by solving a **subproblem**.  
8. Add only the columns with **negative reduced cost** …
=> Submission for group 69: 2352696_2353341_2353027_2352300_2352112

student_submissions/s2352641/policy2352641.py, student_submissions/s2352641_2352742_2353035_2353041/policy2352641_2352742_2353035_2353041.py
Title: 2352641_2352742_2353035_2353041
**===== GROUP MEMBERS =====**
Group 45
2352641 - Mai Trung Kiên
2352742 - Lê Nguyễn Bảo Minh
2353035 - Đoàn Thiên Quý
2353041 - Võ Thị Như Quỳnh
**===== POLICY DESCRIPTION =====**
In both policy, we use MaxRects Algorithm as our base
* Algorithm *
BSSF (1) and BL (2)
BSSF: Best short side fit
BL: Bottom left (top left first)
**===== IMPLEMENTATION =====**
def get_action(...):
Policy implementation (port) from full solution to single solution giver.
Logic:
Since it is ruled that an Observation is done IFF all products are fulfilled,
An Observation is unique when result list is depleted.
If new observation, single solve it then return each product placement sequentially.
def heuristic_2d_csp(...):
call pack_rectangle
wrap results (the entire problem …
=> Submission 2352641_2352742_2353035_2353041

student_submissions/s2353132_2152950_2353081_2353136_2352001/policy2353132_2152950_2353081_2113055_2352001.py
This report examines two algorithms to solve the 2D Cutting Stock Problem: *Art Algorithm* and *Column Generation*. Both algorithms aim to minimize waste while optimizing the arrangement of smaller pieces cut from larger sheets. The Art Algorithm emphasizes geometric accuracy and minimal waste, while Column Generation focuses on iterative improvement of cutting patterns.
| No. | Full Name               | Student ID  |
|-----|-------------------------|-------------|
| 1   | Lê Phước Minh Thiện     | 2353132     |
| 2   | Trần Mãnh Tài           | 2152950     |
| 3   | Võ Nhật Tân             | 2353081     |
| 4   | Bùi Anh Thịnh           | 2353136     |
| 5   | Bùi Khánh An            | 2352001     |
---
Column Generation iteratively identifies efficient cutting patterns and adds them to …
=> Submission (Group 87) 2353132_2152950_2353081_2353136_2352001

student_submissions/s2310210_2310370_2310730_2310624_2312955/policy2310210_2310370_2310730_2310624_2312955.py
**Description:**
Our group implementation provides First_Fit_Decreasing and Best_Fit_Decreasing algorithm to solve a 2D Cutting Stock Problem, where the goal is to place products into available stocks in a way that minimizes the remaining free space. The algorithm attempts to maximize space utilization and reduce fragmentation by selecting the placement that leaves the least wasted space.
**How our code works:**
```1.``` Initialization: We use the __init__ function inherited from Policy that takes in policy_id  to let the program know which algorithm we’ll be using. (policy_id = 1 for FFD and 2 for BFD).
```2.``` Action Selection: The get_action function is mainly used to guide the program to the correct function according to self.policy_id initialized from __init__ 
```a)``` …
=> Submission(group_137)_2310210_2310370_2310730_2310624_2312955

student_submissions/s2310856_2311007_2310992_2311002_2310474/policy2310856_2311007_2310992_2311002_2310474.py
2310856-2311007-2310992-2311002-2310474
1. Introduce Algorithm
- The Best Fit algorithm: provides a heuristic approach to solving this problem by prioritizing the most efficient placement of smaller items into the stock that will result in the least remaining unused material.
- Bottom-Left Fill: is a common heuristic algorithm used in two-dimensional cutting stock problems or bin packing problems, particularly when dealing with rectangular items that need to be placed on a larger rectangular sheet or surface. The goal is to pack items efficiently, minimizing unused space or reducing the number of sheets required.
2. The implementation 
- Trần Anh Hào (2310856) + Trần Quốc Hiền (2310992): best fit
- Trần Gia Hiển (2311002) + Lữ Hoàng Duy (2310474): bottom-left fill
- Ngọ Văn Hiệp …
=> Submission (Group 19) 2310856_2311007_2310992_2311002_2310474

student_submissions/s2353373_2352614_2352785_2353259/policy2353373_2352614_2352785_2353259.py
| Name                 | ID       | Contribution | Done  |
|----------------------|----------|--------------|-------|
| Võ Hoàng Ngân        | 2353373  | Policy 1     | 100%  |
| Nguyễn Hữu Minh Khôi | 2352614  | Policy 1     | 100%  |
| Phạm Nhật Nam        | 2352785  | Policy 2     | 100%  |
| Trần Thuỵ Thuỷ Trúc  | 2353259  | Policy 2     | 100%  |
The First Fit Decreasing (FFD) algorithm is a greedy heuristic designed to approximate solutions to resource allocation problems. In the context of the 2D Cutting Stock Problem, FFD focuses on arranging rectangular pieces on stock sheets to minimize the total number of sheets used while adhering to dimensional and demand constraints. The algorithm is described below:
1. **Sorting:** The products are sorted by their area in descending order. …
=> Submission (Group 14)2353373_2352614_2352785_2353259

student_submissions/s2210xxx/policy_2312593_2312776_2252405_2312701_2213674/policy_2312593_2312776_2252405_2312701_2213674.py
Nhóm 58 nộp mã nguồn bài tập lớn Mô Hinh Hóa Toán Học
Sinh viên:
Nguyễn Thành Phát (leader) - 2312593
Nguyễn Tấn Phước - 2312776
Nguyễn Minh Phúc - 2312701
Nguyễn Phước Trọng -2213674
Nguyễn Tuấn Kiệt - 2252405
=> Group 58 Submission 2312593, 2312776, 2252405, 2312701, 2213674

student_submissions/s2312538_2312232_2312737_2313579_2312765/policy2312538_2312232_2312737_2313579_2312765.py
|STT|Họ và tên| MSSV | 
|---|-----|--------|
| 1 | Ôn Hà Ngọc Như | 2312538 |
| 2 | Phạm Hồng Ngân | 2312232 |
| 3 | Hoàng Quỳnh Phương | 2312737 |
| 4 | Nguyễn Khánh Trinh | 2313579 |
| 5 | Vũ Lê Hà Phương | 2312765 |
Policy của nhóm bao gồm hai giải thuật giải quyết Bài toán cắt vật liệu 2 chiều (2D Cutting Stock Problem): <mark>Giải thuật sinh cột (Column Generation)</mark> và <mark>Giải thuật Heuristic - Phương pháp Fist Fit Decreasing </mark>  
Giải thuật sinh cột là một phương pháp tiếp cận hiệu quả để giải quyết các bài toán quy hoạch tuyến tính lớn. Ý tưởng chính của thuật toán là xây dựng dần dần mô hình giải quyết bằng cách chỉ thêm vào những biến có khả năng cải thiện đáng kể giá trị mục tiêu.
1. Sắp xếp vật phẩm giảm dần theo diện tích.
1. Từ bài toán chính xác định bài toán …
=> Submission - Team 15: 2312538_2312232_2312737_2313579_2312765

student_submissions/s2352216_2352237_2352334_2352475/policy2352216_2352237_2352334_2352475.py
Add submission for Team46 CC06
Trần Lam Biểu - 2352116 (Leader)
Nguyễn Thành Đạt - 2352237 
Nguyễn Duy Khang - 2352475 
Phạm Minh Hiếu - 2352334
=> Assignment-CO2011-CSE241-Team_46

student_submissions/s2312845_2312460_2312665_2312934_2312580/policy2312845_2312460_2312665_2312934_2312580.py
- **Hoàng Giữ Tiến Nhất** (2312460)  
- **Bùi Ngọc Phúc** (2312665)  
- **Nguyễn Đại Phú Sang** (2312934)  
- **Lê Trần Tấn Phát** (2312580)  
- **Nguyễn Trần Anh Quân**(2312845)
---
Column Generation is an optimization technique used in the cutting stock problem to efficiently solve large instances. It decomposes the problem into a **master problem**, which selects cutting patterns, and a **subproblem**, which generates new patterns with negative reduced costs. The algorithm iteratively solves both problems, adding promising patterns to improve the solution until no further improvements are possible, making it effective for large-scale problems.
A metaheuristic inspired by natural selection, used for optimization problems like the 2D Cutting Stock Problem. GA works by creating a …
=> Submission - Group 99 -  2312845  2312460  2312665  2312934  2312580

student_submissions/s2313280_2311382_2310143_2313140/policy2313280_2311382_2310143_2313140.py
| STT | Họ và tên                              | Mã số sinh viên | Lớp |
| ---- | ----------------------------| --------------- |-------|
| 1     | Nguyễn Duy Thịnh           | 2313280         |   L02  |
| 2     | Nguyễn Nhật Thiên Hữu  | 2311382         |   L02  |
| 3     | Phạm Nguyễn Thế Anh    | 2310143         |   L02  |
| 4     | Phạm Tấn Thành              | 2313140         |   L01  |
Nhóm đã hiện thực hai giải thuật sinh cột  (Column Generation) và  giải thuật First Fit để giải quyết bài toán cắt vật liệu 2 chiều (2D Cutting Stock Problem)
1.  Sắp xếp các diện tích mảnh (Prod) giảm dần
2.  Duyệt qua vòng lặp kép, xét từng tấm (Stock), duyệt qua từng mảnh (Prod) 
3.  Sử dụng hàm con để tìm vị trí phù hợp cho mỗi mảnh trong kho, cả khi mảnh đó có thể xoay (rotated). Nếu thỏa thì …
=> Submission - 2313280_2311382_2310143_2313140 - Group 150

student_submissions/s2352068_2352538_2352755_2352911/policy2352068_2352538_2352755_2352911.py
Tran Nam Anh - 2352068  
Nguyễn Hồ Quang Khải (leader) - 2352538  
Nguyễn Tiến Minh - 2352755  
Tán Khánh Phong - 2352911  
The algorithm combines Greedy and Dynamic Programming, with Greedy as the main approach. Greedy makes quick, locally optimal decisions, such as selecting the largest product first to minimize immediate loss. Dynamic Programming then refines the solution by evaluating all possible placements and choosing the one with the smallest trim loss, ensuring the overall solution is optimized for minimal waste.
This algorithms provide a solution by evaluating their fitness based on space utilization and overlap prevention, and evolving better solutions through elite selection, crossover, and mutation operations. 
The algorithm considers both normal and rotated orientations of …
=> Submit policy2352068_2352538_2352755_2352911

student_submissions/s2033338_2310942_2212050_2311176_2212719/policy2033338_2310942_2212050_2311176_2212719.py
| No. | Fullname                   | Student ID |
|-----|----------------------------|------------|
| 1   | Tôn Trọng Tín              | 2033338    |
| 2   | Đinh Tấn Hiếu              | 2310942    |
| 3   | Lương Vĩnh Minh            | 2212050    |
| 4   | Nguyễn Đức Huy             | 2311176    |
| 5   | Nguyễn Trần Như Phước      | 2212719    |
---
| ID           | Execution Time (s) | Filled Ratio | Trim Loss |
|---------------------|---------------------|--------------|-----------|
| Column Generation   | 0.905049562454223  | 0.22         | 0.18782316545138 |
| Genetic Algorithm   | 2.34034373         | 0.34         | 0.30761454     |
This algorithm determines the most optimal cutting pattern for a given stock by starting with a set of initial cutting patterns. It then iteratively …
=> Submission-Group 9: 2033338_2310942_2212050_2311176_2212719

student_submissions/s2313866_2313867_2310975_2310554_2313017/policy2313866_2313867_2310975_2310554_2313017.py
- Dương Khả Vân 2313866: Pull request, implement GA, merge code.
- Giang Phi Vân 2313867: Implement BestFit, fix bugs.
- Nguyễn Thị Quỳnh Tâm 2313037: Research algorithms.
- Thái Trung Hiếu 2310975: Research algorithms.
- Nguyễn Đặng Trí Dũng 2310554: Research algorithms.
My team implemented two algorithms for solving the 2D Cutting Stock Problem: BestFit and Genetic Algorithm (GA).
- **Description**: The BestFit algorithm is a greedy heuristic used for resource allocation problems like the Cutting Stock Problem (CSP). It works by assigning each item to the most suitable space available, ensuring the remaining space is minimized.
- **Key Idea**: Items (or parts) are placed in the bin/pattern where they fit best, without exceeding the bin/pattern's capacity. If no suitable bin exists, a …
=> Submission of group 121. 

student_submissions/s2312264_2312291_2310930_2312589_2313318/policy2312264_2312291_2310930_2312589_2313318.py
Member List:
| Members      | StudentID        |    Contribution    |
|-------------|--------------|--------------|
| Lê Thành Nghĩa  | 2312264   | 100%   |
| Vũ Trọng Nghĩa   | 2312291   | 100%   |
|Nguyễn Huỳnh Thiên Hậu| 2310930|100%|
|Nguyễn Mai Huy Phát|2312589|100%|
|Võ Văn Thịnh|2313318|100%|
Now, we will explain some information about our algorithms to solve the assignment (additionally 3rd algorithm).
The main idea of ​​the Greedy algorithm is to choose the best cutting option at each step, based on a specific criterion, for example optimizing the number of panels used or minimizing the area scrap accumulation. Below is a specific approach to the problem of minimizing scrap area:
1. **Sorting products**: Products are sorted by priority, for example by size largest size or largest …
=> Submission Group 67 2312264_2312291_2310930_2312589_2313318

student_submissions/s2352950_2353169_2352416_2353370_2352881/policy2352950_2353169_2352416_2353370_2352881.py
| **Team Member**         | **Student ID** | **Responsibilities**                       | 
|--------------------------|---------------|--------------------------------------------|
| Lâm Mỹ Phương           | 2352950       | Synthesizing content, writing the report, case study   | 
| Nguyễn Anh Thy           | 2353169       | Algorithms, code implementation, performance evaluation | 
| Võ Quang Huy             | 2352416       | Algorithms, code implementation, performance evaluation | 
| Trần Thanh Như Ý         | 2353370       | Algorithms, code implementation, performance evaluation | 
| Trương Anh Phan          | 2352881       | Literature review, theoretical foundation  |
This submission addresses the Two-Dimensional Cutting Stock Problem (2D-CSP), a classical optimization problem …
=> Submission_Team_58_2352950_2353169_2352416_2353370_2352881

student_submissions/s231215_2311197_2311111_2310689_2313323/policy231215_2311197_2311111_2310689_2313323.py, student_submissions/s231215_2311197_2311111_2310689_2313323/requirements.txt
1. 2312153 - Dương Hồ Nam
2. 2311197 - Nguyễn Nhật Huy
3. 2311111 - Bành Phú Hội
4. 2310689 - Phạm Tấn Đạt
5. 2313323 - Trần Lê Gia Thoại
This submission contains two separated algorithm, Best-Fit Heuristic và Reinforcement Learning
The aim is create optimize solution with Best-Fit Heuristic, while trying to force model RL to adapt and produce acceptable optimization result.
The Best Fit Heuristic for the 2D Cutting Stock Problem (2D CSP) is a placement strategy where each item (product) is placed in the stock sheet that leaves the least leftover space after the item is packed. This heuristic aims to minimize wasted space by finding the stock sheet that is best suited for the current item, considering its dimensions. The approach typically involves evaluating all available stock sheets …
=> Submission of Group 11 (2312153, 2311197, 2311111, 2310689 and 2313323)

student_submissions/s2311787_2312514_2420004_2211155_2313562/policy2311787_2312514_2420004_2211155_2313562.py
| Name         | Student ID      | Contribution      | Workload |
|:-------------------|:----------------|:----------------|:----------------|
| Trần Tuấn Kiệt (leader)    | 2311787  | Code and Conclusions | 20%|
| Trương Văn Thảo Nhi     | 2312514   | Code and Latex| 20%|
| Trương Thế Khải    | 2420004   | Code and Analyze Results   |20%|
| Dương Gia Huy    | 2211155   | Case Study  |20%|
| Ngô Minh Triết   |  2313562     | Modeling   |20%|
The Greedy Algorithm is a heuristic approach used to solve the Cutting Stock Problem by iteratively minimizing waste during the cutting process. It operates by making locally optimal decisions at each step to fit items into stocks efficiently. The steps are as follows:
1.  **Item Sorting:**
Items are sorted based on a specific priority criterion, such …
=> Submissions_Group173_2311787_2312514_2420004_2211155_2313562

student_submissions/s2352619_2353046_2352422_2353275_2352615/policy2352619_2353046_2352422_2353275_2352615.py
1.	Policy description: Our group implement the Random, DP (Dynamic Programming), Backtracking and Greedy algorithm:
•	Random Policy: It randomly places items on the stock material without any specific strategy or optimization.
•	Dynamic Programming (DP): It breaks down the problem into smaller subproblems and uses a table to store previously calculated results to avoid redundant computations.
•	Backtracking: It systematically explores potential placements and backtracks when a placement is not feasible, ensuring a comprehensive search of the solution space.
•	Greedy Policy: Makes locally optimal choices at each step, aiming to find a reasonable solution quickly without guaranteeing global optimality.
2.	The commits of team members:
•	Nguyễn Ngọc Sáng (2353046): Lead implementation and …
=> Submission-Group_81_2352619_2353046_2352422_2353275_2352615

student_submissions/s2310510_2312506_2310167_2313914/policy2310510_2312506_2310167_2313914.py, student_submissions/s2310510_2312506_2310167_2313914/requirements.txt
1. Phạm Khánh Duy - 2310510 (TN01, Nhóm trưởng)
2. Nguyễn Trần Yến Nhi - 2312506 (TN01)
3. Tăng Hồng Ái - 2310167 (TN01)
4. Lê Phan Khải Vinh - 2313914 (TN01)
Nhóm hiện thực class Policy2310510_2312506_2310167_2313914 bao gồm 2 giải thuật: Giải thuật Advantage Actor-Critic (policy_id = 1) và Giải thuật quy hoạch tuyến tính nguyên (policy_id = 2).
Giải thuật A2C là sự kết hợp giữa hai thành phần: actor và critic, mỗi thành phần có một vai trò quan trọng trong quá trình học tập. Trong đó, actor sẽ có trách nhiệm lựa chọn hành động trong môi trường, có nghĩa là chính sách mà tác nhân sẽ sử dụng. Trong khi đó,  critic sẽ đánh giá chất lượng của hành động mà actor lựa chọn thông qua việc tính toán giá trị của trạng thái hiện tại, từ đó cải thiện chính sách của tác nhân.
Dựa trên mô hình bài …
=> Submission Group 69 - Students' IDs: 2310510 - 2312506 - 2310167 - 2313914

student_submissions/s2352378_2352977_2252100_2352012_2352130/algorithms.py, student_submissions/s2352378_2352977_2252100_2352012_2352130/policy2352378_2352977_2252100_2352012_2352130.py, student_submissions/s2352378_2352977_2252100_2352012_2352130/product_list.py, student_submissions/s2352378_2352977_2252100_2352012_2352130/requirements.txt, student_submissions/s2352378_2352977_2252100_2352012_2352130/stock.py
Our policy includes 2 heuristic algorithms to solve the Cutting Stock problem:
Branch and Bound (`policy_id = 1`): A systematic method to solve optimization problems, recursively generating cutting patterns to minimize wasted material.
First Fit Decreasing Height (`policy_id = 2`): A greedy heuristic that sorts products by height in descending order and places them into stocks while ensuring a tight fit.
Upon initialization, the algorithm sets up empty lists to manage product placements and stock usage. It handles actions via the `get_action` method, which either returns a precomputed action or generates a new list of actions using `generate_list_actions`.
- `get_action()`: Manages the action list and generates new actions when required. Prints debug information about the current state of …
=> Group 17's submission - Student IDs: 2352378_2352977_2252100_2352012_2352130

student_submissions/s2313485_ 2310037_ 2312501/policy2313485_ 2310037_ 2312501.py, student_submissions/s2313485_ 2310037_ 2312501/requirements.txt
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/VICTUS/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/VICTUS/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/VICTUS/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">
</head>
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>
<p class=MsoNormal><b><span lang=VI …
=> Submission (Group 65): 2313485_2310037_ 2312501

student_submissions/s2352291_2352268_2352328/policy2352291_2352268_2352328.py
Phạm Tấn Đức - 2352268
Châu Hùng Hào - 2352291
Nguyễn Công Hiếu - 2352328
**1/ Heuristic - Best Fit approach:**
This algorithm is a heuristic approach that incorporates Best-Fit characteristics to efficiently
solve the 2D-CSP. The core idea of the algorithm is to prioritize larger products in the cut-
ting process, optimizing stock usage while minimizing trim loss. Below is an overview of the
methodology, followed by a detailed analysis of the steps involved in the process.
A example test:
**2/ Dynamic Programming:**
The algorithm described in this section solves the 2D problem by efficiently placing products
in available stock spaces, considering their dimensions and quantities. The steps involved in-
clude generating product sizes, calculating stock fit, updating the cache, and …
=> Submission Group 88: 2352291_2352268_2352328

student_submissions/s2311512_2311525_2311572_2312188_2313467/policy2311512_2311525_2311572_2312188_2313467.py
1. Danh sách thành viên nhóm 114
-  Nguyễn Đăng Khánh – 2311512 ( Group L04- Leader): Xây dựng thuật toán Reinforcement Learning
-  Nguyễn Vũ Duy Khánh – 2311525 ( Group L04 ): Xây dựng các hàm sắp xếp trong First Fit Decreasing
-  Đặng Ngọc Khiêu – 2311572 ( Group L04 ) : Tính toán reward và xác định các hệ số học, tỉ lệ giảm, hình phạt,... phù hợp 
-  Phạm Hoàng Nam – 2312188 ( Group L02 ): Xây dựng thuật toán First Fit Decreasing
-  Triệu Quốc Tính – 2313467 ( Group L03 ): Nghiên cứu, tìm tài liệu các giải thuật
2. Mô tả giải thuật
2.1 First Fit Decreasing
Giải thuật First Fit Decreasing (FFD) là một phương pháp heuristic phổ biến để giải quyết bài toán cắt vật liệu. Thuật toán này là một biến thể của phương pháp First Fit, trong đó sản phẩm được sắp xếp trước theo thứ tự giảm dần về …
=> Submission_nhom_114_2311512_2311525_2311572_2312188_2313467

student_submissions/s2310761_2310744_2310133_2310561_2310735/policy2310761_2310744_2310133_2310561_2310735.py, student_submissions/s2310761_2310744_2310133_2310561_2310735/requirements.txt
**Danh sách thành viên nhóm 159**
| Họ và tên | MSSV |Contribution|
|------------|--------|----|
| Phạm Đình Được (nhóm trưởng)| 2310761 |100%|
| Trần Phương Đỉnh | 2310744 |100%|
| Nguyễn Vũ Mai Anh | 2310133 |100%|
| Nguyễn Tấn Dũng | 2310561 |100%|
| Trần Minh Đăng | 2310735 |100%|
Bài toán cắt vật liệu hai chiều (2D Cutting Stock Problem) là một dạng của bài toán cắt vật liệu, trong đó một số tấm vật liệu lớn cần được cắt thành các mảnh chi tiết nhỏ hơn, có kích thước và số lượng cho trước. Yêu cầu của bài toán là tìm cách hoàn thành công việc cắt trên để lượng vật liệu bị lãng phí là ít nhất.
Nhóm sinh viên sử dụng 2 giải thuật là First Fit Decreasing và Best Fit Decreasing.
**First Fit Decreasing** (FFD, policy_id = 1) là giải thuật greedy, trong đó với mỗi mảnh chi tiết được xét …
=> Submission for group 159: 2310744_2310133_2310761_2310561_2310735

student_submissions/s2352986_2352421_2352901_2352954_2214089/policy2352986_2352421_2352901_2352954_2214089.py
| Name | Workload |
| --------------- | --------------- | 
| Bùi Đình An Lộc (2214089) – Leader | Research and implemented Gurel's Algorithm;<p>contributed to theoretical understanding. |
| Nguyễn Kim Hoàng Phi (2352901) | Researched and implemented Split Fit Algorithm;<p>contributed to theoretical understanding. |
| Hồ Huy Hùng (2352421) | Explored the theoretical and functional aspects<p>of the Split Fit Algorithm. |
| Nguyễn Hồ Minh Phương (2352954) | Explored the theoretical and functional aspects<p>of Gurel's Algorithm. |
| Đinh Hoàng Quân (2352986) | Compiled the final report, addressed questions,<p>and designed test cases for performance evaluation. |
> _Split Fit Algorithm (SF):
- Organized products into wide (width > height) and tall (width ≤ height) groups.
- Optimized stock …
=> Submission 2352986_2352421_2352901_2352954_2214089 (Group 73)

student_submissions/s2313640_2213689_2312185_2212279_2312912/policy2313640_2213689_2312185_2212279_2312912.py
1. Description:
•	Below are the two algorithms we use to solve the CSP problem
+ Column Generation: This algorithm is based on repeatedly solving the problem modeled in a discretized form as a linear programming (LP) relaxation. Using the dual solution values, new “columns” (cutting patterns) with negative reduced costs are generated. The iterative process stops when no more cost-reducing columns can be found, thereby producing a near-optimal solution for the 2D cutting stock problem.
+ Simulated Annealing: This algorithm starts from an initial solution (obtained using heuristics like First Fit Decreasing), and then attempts rearrangements, i.e., “neighbor” solutions by changing cutting positions. If a new solution is better, it is immediately accepted; if it is worse, it may still be …
=> Submission (Group 31): 2313640_2213689_2312185_2212279_2312912

student_submissions/s2433042_2312763_2211199_2211299_2213444/README.md, student_submissions/s2433042_2312763_2211199_2211299_2213444/policy2433042_2312763_2211199_2211299_2213444.py
This is the submission of group 76, comprised of 5 members for the assignment of the subject Mathematical Modeling.
The submission is included in the file student_submission/s2433042_2312763_2211199_2211299_2213444, and is composed of two files: policy2433042_2312763_2211199_2211299_2213444.py and README.md.
=> Group76 - 2433042_2312763_2211199_2211299_2213444

student_submissions/s2212429_2211588_2212937_2212466/policy2212429_2211588_2212937_2212466.py
| STT  | Họ và tên | MSSV | Mail | Lớp |
| ---- | ------------- | ----- | ---- | ---- |
| 1    | Lê Phan Bảo Như | 2212466  | nhu.lez055466 | L01  |
| **2**  | **Lâm Nữ Uyển Nhi** | **2212429** | **nhi.lamlnun** | L01  |
| 3    | Hồ Đăng Khoa | 2211588  | khoa.ho2211588 | L01  |
| 4    | Hoàng Sĩ Xuân Sơn | 2212937  | son.hoang2212937 | L01  |
---
**Mô tả:**
Thuật toán dựa trên ý tưởng của bài toán *2D Bin Packing Problem* với nhiều kích thước thùng (*bin*) khác nhau.
- **Sắp xếp:** Các **stock** được xếp theo chiều diện tích giảm dần, cùng diện tích thì chu vi tăng dần. Các **item** được xoay sao cho chiều rộng lớn hơn chiều dài. Các item được xếp theo chiều rộng giảm dần, cùng chiều rộng thì theo chiều cao giảm dần.
---
**Mô tả:**
Thuật toán dựa trên ý tưởng của thuật toán *Greedy* để …
=> Submissions - Group 23 : 2212429_2211588_2212937_2212466

student_submissions/s2352178_2352182_2353057_2352254/policy2352178_2352182_2353057_2352254.py
This code defines a class `Policy2352178_2352182_2353057_2352254` that inherits from an abstract `Policy` class. It implements two different strategies for solving a 2D bin packing problem, where the goal is to place rectangular products onto rectangular stock materials in an efficient way. The policy to be used is selected via a `policy_id` during initialization (either 1 or 2).
**Policy 1: First-Fit with Orientation Optimization**
*   **Description:** This policy attempts to place products into the first available stock where they fit, starting with the largest products and the largest stocks (based on area). Before placing, it considers two orientations of each product: the original orientation and a 90-degree rotated version. It then calculates a metric (l1 and l2) to estimate which …
=> Group 49: 2352178_2352182_2353057_2352254

student_submissions/s2352966_2353104_2353316/policy2352966_2353104_2353316.py
Trần Công Hoàng Phước - 2352966
Tăng Công Thành - 2353104 
Nguyễn Văn Viết - 2353316 
In this large assigment, we only choose two algorithm to solve the problems. Those are Best Fit Algorithm and FFD Algorithm
The First Fit Decreasing (FFD) Algorithm is a greedy heuristic approach designed for bin-packing problems like 2D-CSP. 
The Best Fit (BF) Algorithm is a heuristic method aimed at solving bin-packing problems like 2D-CSP
Test data: 
seed = 42
FFD: trim loss: 0.4375042357578645
BF: trim loss: 0.3553882983059738
seed = 1
FFD: trim loss: 0.19448476701547693
BF: trim loss: 0.19578219132563987
seed = 2
FFD: trim loss: 0.20333233014380683
BF: trim loss: 0.051662039804688656
=> 232966_2353104_2353316 Team 44

student_submissions/s2353084_2352765_2353044/policy2353084_2352765_2353044.py
Group members:
Phan Bá Thanh - 2353084
Trịnh Lê Minh - 2352765
Trần Phước Sang - 2353044 
Our submission includes 2 algorithms: First Fit Decreasing (FFD) and Hybrid.
- FFD:  (First-Fit Decreasing) algorithm is a heuristic approach for solving the bin packing problem, where the goal is to pack a set of items into the fewest number of bins, each with a fixed capacity. It combines the First-Fit strategy with a preprocessing step where items are sorted in decreasing order of size.
- Hybrid: is the algorithm we aim to combine the strengths of popular strategies such as Best-Fit and First-Fit.
The implementation is in policy2353084_2352765_2353044.py
Comparison
=> 2353084_2352765_2353044

student_submissions/s2312266_2312040_2313953_2312818_2313341/policy2312266_2312040_2313953_2312818_2313341.py
This pull request introduces two algorithms developed by Team 105 for optimizing strip packing within stock sheets: Branch and Bound (BnB) and Simulated Annealing (SA). The team consists of Nguyễn Đức Nghĩa (2312266), Lê Minh Mẫn (2312040), Lâm Hoàng Vũ (2313953), Đặng Đình Thiên Quân (2312818), and Nguyễn Hữu Thời (2313341), who collaborated to design and implement these efficient methods. These algorithms aim to maximize space utilization, minimize trim loss, and improve runtime performance.
**Team members**
No. | Full Name | Student ID | % Done
-- | -- | -- | --
1 | Nguyễn Đức Nghĩa | 2312266| 100%
2 | Lê Minh Mẫn| 2312040| 100%
3 | Lâm Hoàng Vũ | 2313953| 100%
4 | Đặng Đình Thiên Quân | 2312818| 100%
5 | Nguyễn Hữu Thời | 2313341| 100%
**Algorithms overview**
*Branch and Bound* is an …
=> Submission Group_105 - 2312266_2312040_2313953_2312818_2313341

student_submissions/s2312001_2311896_2312159_2312689_2312168/policy2312001_2311896_2312159_2312689_2312168.py
|Họ và tên  |MSSV  |
|---|---|
|Ngô Chí Lực|2312001|
|Huỳnh Hồ Nam|2312159|
|Mai Xuân Phúc|2312687|
|Đỗ Quang Long|2311896|
|Nguyễn Chu Hải Nam|2312168|
2D Cutting Stock Problem (2D-CSP) là một bài toán phân hoạch tuyến tính 2 chiều với mục tiêu là giảm thiểu số lượng mảnh vật liệu stock làm sao cho vẫn đáp ứng đủ số lượng sản phẩm và yêu cầu. Bài toán có nhiều giải thuật khác nhau để giải. Trong phần nộp bài của nhóm tác giả, nhóm tác giả sẽ trình bày 2 giải thuật Policy là Best Fit (policy_id = 1) và Hybrid First Fit (policy_id = 2).
Best Fit (BF) và Hybrid First Fit đều là các giải thuật heuristic, tức có nghĩa ta không cố gắng để tìm một kết quả chính xác - một kết quả tối ưu (exact solution) mà thay vào đó ta sẽ tối ưu việc lựa chọn nơi để đặt các stock, sao cho tối ưu hóa được phần …
=> Submission Group 95: 2312001 2311896 2312159 2312689 2312168

student_submissions/s2310097_2312963_2310577_2213195_2310052/policy2310097_2312963_2310577_2213195_2310052.py, student_submissions/s2310097_2312963_2310577_2213195_2310052/requirements.txt
| Name               | Student ID | Contribution                    |
|--------------------|------------|----------------------------------|
| Nguyen Hoang Anh   | 2310097    | Implemented SARSA Algorithm     |
| Nguyen Hong Son    | 2312963    | Problem Formulation and learn algorithms |
| Vo Hung Dung       | 2310577    | Case Study                      |
| Long Dien Thang    | 2213195    | Case Study                      |
| Bui Duy Anh        | 2310052    | Implemented Genetic Algorithm   |
---
SARSA is an on-policy reinforcement learning algorithm used to solve Markov Decision Processes. It learns a policy by estimating Q-values for state-action pairs and updating them iteratively based on observed transitions.
**Key Steps**:  
1. Initialize Q-values for all state-action pairs.  
2. …
=> Submission - Group 101 - 2310097_2312963_2310577_2310052

student_submissions/s2352151_2352633_2352027_2352380_2353015/policy2352151_2352633_2352027_2352380_2353015.py
| Họ và Tên | MSSV | Ghi chú |
|--------|--------|--------|
| Trần Phú Cường | 2352151 | Nhóm trưởng |
| Trương Minh Khuê | 2352633 | |
| Đặng Thế Lâm Anh | 2352027 | |
| Huỳnh Nguyễn Nhật Huy | 2352380 | |
| Trần Bá Minh Quân | 2353015 | | 
Đây là một thuật toán heuristic hữu ích để giải quyết bài toán cắt vật tư. BFD tìm cách giảm thiểu lãng phí không gian bằng cách ưu tiên xếp đoạn cắt vào tấm vật liệu có chỗ trống phù hợp nhất.
1.  Sắp xếp giảm dần các yêu cầu cắt: Các đoạn cần cắt được sắp xếp theo thứ tự giảm dần về kích thước (diện tích = chiều rộng × chiều cao). Nếu các đoạn có cùng diện tích, ưu tiên đoạn có số lượng lớn hơn.
2. Áp dụng thuật toán BFD: Với mỗi đoạn trong danh sách đã được sắp xếp, thuật toán sẽ lần lượt kiểm tra tất cả các tấm vật liệu hiện có. Đoạn cắt sẽ được …
=> submission_2352151_2352633_2352027_2352380_2353015-Group 27

student_submissions/s2312485_2312167_2313422_2312184_2312196/policy2312485_2312167_2313422_2312184_2312196.py
This pull request presents an enhanced solution for the Two-Dimensional Cutting Stock Problem (2DCSP), incorporating two unique algorithmic strategies: the LargestFirst and Best-Fit heuristic placement methods.
*Brief description of policy*
1. LargestFirst Policy:
- This strategy prioritizes placing the largest products first.
- Products are sorted in descending order based on their area (width × height), ensuring that larger products are considered for placement before smaller ones.
- Stocks are also sorted in descending order by their total area and width to prioritize larger and wider stock containers.
- For each product and its rotations, it tries to find the first feasible placement in the available stocks, scanning the stock in a top-left-first manner.
- The search stops as soon as …
=> Submission_Group113_2312485_2312167_2313422_2312184_2312196

student_submissions/s2210xxx/s_2313257_2111682_2313101_2014717_1832026/policy2313257_2111682_2313101_2014717_1832026.py, student_submissions/s2313257_2111682_2313101_2014717_1832026/policy2313257_2111682_2313101_2014717_1832026.py
| Họ và tên | Mã số sinh viên | Công việc |
| --- | ----------- | ----------- |
| Bùi Phước Thịnh | 2313257 | Hoàn thành báo cáo & mô hình hóa bài toán |
| Lý Thanh Tiến | 2014717 | Code thuật toán 1 & mô hình hóa bài toán |
| Trần Ngọc Châu Long | 2111682 | Hoàn thành báo cáo & mô hình hóa bài toán |
| Nguyễn Minh Thái | 2313101 | Nghiên cứu và tóm tắt thuật toán 1 & mô hình hóa bài toán |
Bài toán cắt vật liệu 2 chiều (2D Cutting Stock Problem) là một loại bài toán tối ưu hóa trong đó
mục tiêu là cắt các sản phẩm hình chữ nhật nhỏ hơn từ các tấm vật liệu hình chữ nhật ban đầu sao cho tối thiểu lượng vật liệu bị bỏ đi (không thể dùng để cắt bất kì sản phẩm nào khác) hoặc số lượng tấm vật liệu phải sử dụng. Bài toán này phổ biến trong các ngành công nghiệp như sản xuất, dệt may và đóng …
=> Submissions - Group 35 : 2313257, 2111682, 2313101, 2014717

student_submissions/s2310373_2013452_2311958_2312137_2313045/policy2310373_2013452_2311958_2312137_2313045.py
| No. | Full Name        | Student ID | % Done Tasks | % Contribution | Tasks                                                     |
|-----|------------------|------------|--------------|----------------|-----------------------------------------------------------|
| 1   | Nguyễn Thành Công| 2310373    | 100%         | 20%            | - Xây dựng cơ sở lý thuyết<br>- Mô hình hóa bài toán      |
| 2   | Đào Quốc Khánh   | 2013452    | 100%         | 20%            | - Nghiên cứu & hiện thực giải thuật 1 (Genetic Algorithm)                |
| 3   | Nguyễn Thanh Lộc | 2311958    | 100%         | 20%            | - Xây dựng cơ sở lý thuyết cho bài toán<br>- Soạn báo cáo LaTex |
| 4   | Bành Tiểu My     | 2312137    | 100%         | 20%            | - Tìm kiếm case study<br>- Write LaTeX for …
=> 2310373_2013452_2311958_2312137_2313045

student_submissions/s2310653_2313906_2312010_2312498_2313729/policy2310653_2313906_2312010_2312498_2313729.py
| STT | Họ tên              | MSSV | Lớp |
|-----|-----------------------|------------|------------|
| 1   | Lê Tiến Đạt           | 2310653    | L03    |
| 2   | Đoàn Công Vinh         | 2313906    | L03   |
| 3   | Nguyễn Lê Thảo Ly     | 2312010    | L03    |
| 4   | Lê Hoàng Thảo Nhi     | 2312498    | L04    |
| 5   | Giang Huy Tuấn        | 2313729    | L04   |
**GIẢI THUẬT FIRST-FIT DECREASING**
1. Sắp xếp cách sản phẩm (product) theo thứ tự giảm dần về diện tích (area = width x height).
2. Duyệt qua vòng lặp từng sản phẩm (product) để tìm thấy sản phẩm tiếp theo
3. Duyệt qua từng nguyên liệu (stock sheet/material). 
4. Tại từng stock, tiếp tục dùng vòng lặp để  kiểm tra sản phẩm ở cả hai trạng thái: không xoay và xoay 90 độ.
5. Sử dụng hàm con tìm vị trí phù hợp để đặt product. …
=> Submission_Team_56_2310653_2313906_2312010_2312498_2313729

student_submissions/s2312900_2310559_2420003_2312894_2312974/policy2312900_2310559_2420003_2312894_2312974.py, student_submissions/s2312900_2310559_2420003_2312894_2312974/requirements.txt
|  Name             | Student ID | Problem | 
| :---------------:|:------------:|:---------:|
| Phạm Duy Quý | 2312900 | Research First Fit Decreasing, write report| 
| Nguyễn Võ Đức Sơn | 2312974 | Rescreach First Fit Decreasing, source code implementation |
| Huỳnh Kim Quý | 2312894 | Research Simulated Annealing, source code implementation|
| Nguyễn Huy Hoàng | 2420003 | Research Simulated Annealing, source code implementation | 
| Nguyễn Phạm Mạnh Dũng | 2310559 | Case study, write report |
The First Fit Decreasing (FFD) algorithm is a greedy heuristic widely used for solving the 2D Cutting Stock Problem, where the goal is to minimize material waste when cutting smaller items from larger stock sheets. The algorithm begins by sorting the items in descending order based on their sizes …
=> Group160_2312900_2310559_2420003_2312894_2312974 

student_submissions/s2320001_2312119_2312065_2312696_2312861/policy2320001_2312119_2312065_2312696_2312861.py
This pull request illustrates the implementation of a policy addressing the Two-Dimensional Cutting Stock Problem ( 2D CSP)
| Name                     | ID      | Contribution | % Done |
|--------------------------|---------|--------------|--------|
| Nguyễn Tiểu Anh          | 2320001 | Policy 2             |100        |
| Trần Hồ Hải Minh         | 2312119 | Policy 2             | 100 |
| Kiều Tấn Anh Minh        | 2312065 | Policy 2             | 100       |
| Nguyễn Huy Phúc          | 2312696 | Policy 1             | 100       |
| Văn Thái Quân             | 2312861 | Policy 1             | 100       |
**Policy 1: First Fit algorithm**
The First Fit algorithm allocates products to stocks by placing each product in the first suitable position.This algorithm is simple yet effective, …
=> Submission group 5 - 2320001_2312119_2312065_2312696_2312861

student_submissions/s2352113_2352103_2352740_2352570_2352442/policy2352113_2352103_2352740_2352570_2352442.py
Policy
The Cutting Stock Problem focuses on cutting large stock materials into smaller pieces of specified lengths while minimizing waste. In this 2D Cutting Stock Problem, a distinctive feature is that all the shapes of the products and stocks are rectangular. This makes it highly suitable for applying heuristic algorithms, which produce fast results with high accuracy. In particular, the FFD (First Fit Decreasing) and BFD (Best Fit Decreasing) algorithms are especially effective.
• The FFD algorithm is well-suited for case studies that aim to minimize the number of stocks used.
• The BFD algorithm is ideal for cases where minimizing material waste is the priority.
Implementation
FFD:
• FFD sorts the stocks and products in descending order of size.
• For each piece, it places it in the …
=> Submission (Group 57): 2352113_2352103_2352740_2352570_2352442

student_submissions/s2352685_2352392_2352540_2353079/policy2352685_2352392_2352540_2353079.py, student_submissions/s2352685_2352392_2352540_2353079/requirements.txt
Bùi Huỳnh Long - 2352685 (Group CN02 - Team 33)
Nguyễn Hồng Huy - 2352392 (Group CN02 - Team 33)
Phạm Đăng Khải - 2352540 (Group CN02 - Team 33)
Nguyễn Thanh Tân - 2353079 (Group CN02 - Team 33)
Double DQN is a reinforcement learning algorithm used to minimize material waste in the Cutting Stock Problem by learning optimal cutting patterns. It employs:
Q-Network: Estimates the value of actions.
Target Network: Stabilizes learning.
Replay Buffer: Stores past actions for training.
Advantages: Low material waste, effective for complex problems.
Limitations: Requires high computational power and training time.
FFD is a heuristic algorithm that sorts items by size (largest to smallest) and places each into the first available material sheet.
Advantages: Simple, fast, and easy to implement. …
=> Submission Group 33: 2352685_2352392_2352540_2353079

student_submissions/s2313342_2310569_2313237_2311159_2310497/policy2313342_2310569_2313237_2311159_2310497.py
Brief description of our policy
•	Column Generation Algorithm:
This is an optimization technique commonly used to solve large-scale linear programming problems, such as assignment problems, bin packing problems, or routing problems. The algorithm focuses on a subset of "meaningful" variables rather than handling the entire variable space. It gradually adds necessary variables to the model through subproblems, allowing for efficient optimization without excessive computational cost.
•	First-Fit Decreasing (FFD) Algorithm:
FFD is a heuristic algorithm often used to solve the Bin Packing Problem. The algorithm consists of two main steps: first, it sorts the items in decreasing order of size; then, it sequentially places each item into the first bin that has enough space. If no bin has enough …
=> Subsmissions - Group 117 - 2313342-2310569-2313237-2311159-2310497

student_submissions/s2311557_2312157_2210112_2210302_2313127/policy2311557_2312157_2210112_2210302_2313127.py
1. Tên thành viên
-Nguyễn Quốc Khải _ 2311667 - Leader : Xây dựng thuật toán FFD , mô hình hóa và làm case study
-Hồ Bắc Nam - 2312157 : Xây dựng thuật toán BFD và hoàn thành báo cáo
-Nguyễn Tuấn Anh - 2210112 : Không đóng góp
-Nguyễn Trí Thành - 2313127 : Không đóng góp
-Đoàn Đức Bình - 2210302 : Không đóng góp
2. Mô tả giải thuật
-Giải thuật First Fit Decreasing (FFD) :
• Đầu tiên sắp xếp danh sách sản phẩn theo thứ tự diện tích giảm dần. Mục đích của việc
sắp xếp này để tránh trường hợp các sản phẩm nhỏ được cắt trước, các sản phẩm lớn phía
sau không còn đủ nguyên liệu để cắt nữa.
• Lần lượt duyệt qua các sản phẩm đã được sắp xếp. Đối với mỗi sản phẩm, lần lượt duyệt
qua các stoke , tìm stoke phù hợp để cắt . Nếu stock có đủ nguyên liệu để cắt thì cắt. Nếu
không , xoay sản phẩm và tiếp …
=> Resubmission_group_143_2311557_2312157_2210112_2210302_2313127

student_submissions/s2210517_2210050_2210077_2210707/policy2210517_2210050_2210077_2210707.py
Column Generation and RL Algorithm
=> Submition Group 60 2210517_2210050_2210077_2210707

s2352467_2352333_2352930_2352553_2352339/policy2352467_2352333_2352930_2352553_2352339.py
Thực hiện bởi: 
Hồ Bá  Khang_2352467
Huỳnh Thiên Phúc_2352930
Đinh Trần Anh Khoa_2352553
Nguyễn Ngọc Minh Hiền_2352339
Phạm Hoàng Minh Hiếu_2352333
Repository này chứa mã nguồn triển khai một chính sách tối ưu hóa bài toán cắt stock bằng hai phương pháp khác nhau: *Quy Hoạch Động (Dynamic Programming - DP)* và *First-Fit Decreasing (FFD)*. Cả hai phương pháp đều được thiết kế để giải quyết bài toán cắt stock 2D, với mục tiêu *tối đa hóa diện tích sử dụng hiệu quả của các vật liệu stock* thông qua việc sắp xếp các sản phẩm hình chữ nhật.
---
Chính sách cung cấp hai phương pháp tiếp cận:
- Sử dụng chiến lược đệ quy kết hợp với *memoization* để duyệt qua toàn bộ trạng thái cắt có thể.
- Đảm bảo tìm được *lời giải tối ưu* bằng cách kiểm tra mọi cách sắp xếp sản phẩm.
- Phù hợp với bài toán …
=> Submission_2352467_2352333_2352930_2352553_2352339_Group51

student_submissions/s2352921_2353283_2352129_2352659_2352948/policy2352921_2353283_2352129_2352659_2352948.py
**Team Members**
---
| Name | Student ID | Contribution |
| --- | --- | --- |
| Pham Tran Gia Phu | 2352921 | Implemented Genetic Algorithm |
| Vo Hoang Anh Kiet | 2352659 | Implemented Genetic Algorithm |
| Nguyen Tran Trong Tuyen | 2353283 | Implemented First-Fit Decreasing Algorithm |
| Nguyen Huu Cau | 2352129 | Problem Formulation |
| Bui Huy Phuong | 2352948 | Theories & Case Studies |
**Brief Description**
---
This submission introduces two policy implementations for the cutting stock problem:
- Genetic algorithm: The Genetic algorithm in the document is designed to solve the two-dimensional rectangular cutting stock problem (2DRSSSCSP) with the objective of balancing material utilization and cutting complexity. It uses a combination of two-staged patterns (2SGP) and three-staged …
=> Resubmission - Group 53: 2352921, 2353283, 2352129, 2352659, 2352948

student_submissions/s2250013_2352750_2353056_2252731/policy2250013_2352750_2353056_2252731.py
This pull request introduces two advanced approaches for solving the 2D cutting stock problem: the **Greedy Policy** and the **Column Generation Policy**. These methods have been carefully designed, implemented, and tested to ensure optimal performance across various scenarios.
---
- **Greedy Policy**: A straightforward approach aimed at minimizing trim loss through heuristic decision-making.  
- **Column Generation Policy**: A sophisticated method leveraging advanced optimization techniques for superior results.
---
- **Seed Range**: 0 to 9  
- **Epochs**: 100  
| **Metrics**                | **Greedy (Baseline)** | **Random (Baseline)** | **Greedy (Policy1)** | **Column Generation (Policy2)** |
|----------------------------|-----------------------|-----------------------|---------------- …
=> Submission (Group 80): 2250013 - 2352750 - 2353056 - 2252731

student_submissions/s2312449_2312357_2312397_2312435_1652242/policy2312449_2312357_2312397_2312435_1652242.py
**TITLE:
STUDENT ID:** 
2312449_PHẠM HỒNG NHÂN
2312357_NGUYỄN CẢNH NGUYÊN
2312397_LÊ BÁ NGUYỄN
2312435_NGUYỄN MẬU ĐỖ THÀNH NHÂN
1652242_NGUYỄN HỮU GIA HUY
**Brief Description
First Fit Decreasing (FFD):**
The First Fit Decreasing (FFD) policy is a heuristic for solving the 2D-cutting-stocks problem. It works as follows:
1.	The input products are sorted in descending order by size.
2.	The stocks are sorted in ascending order by size.
3.	For each product:
•	Iterate over the stocks (sorted in ascending order).
•	Place the product into the first stock that has enough remaining capacity.
•	If no suitable stock is found, skip this product and handle the remaining.
This policy prioritizes speed and simplicity, making it efficient for large-scale datasets.
**Best Fit Decreasing (BFD):
The Best …
=> Resubmission of (group 155) 2312449_2312357_2312397_2312435_1652242

student_submissions/s2352395_2252563_2353024_2352192_2352707/policy2352395_2252563_2353024_2352192_2352707.py
1. Member list:
Nguyễn Quang Huy - 2352395
Nguyễn Phúc Nhân - 2252563
Hồ Minh Quốc - 2353024
Phạm Quang Anh Duy - 2352192
Vũ Hoàng Long - 2352707
2. Brief Description
Our submission introduces two policies designed to address the 2D cutting stock problem:
- Policy 1: Greedy Best-Fit Algorithm
This policy leverages a greedy approach, focusing on minimizing wasted space. Products are sorted by descending area, similar to the Bottom-Left Algorithm. However, instead of placing products sequentially, the algorithm evaluates all available stocks to identify the one with the least wasted space for each product. If no suitable placement is found, the product is rotated and rechecked. This policy runs slower than Bottom-Left but achieves better space utilization.
- **Policy 2**: Bottom-Left …
=> Submission (Group 63) 2352395_2252563_2353024_2352192_2352707

student_submissions/s_2312596_2313097_2311318_2312954_2312791/policy_2312596_2313097_2311318_2312954_2312791.py
| Full Name | Student ID |
|--------|--------|
| Trần Đỗ Đức Phát (Leader ) | 2312596 |
| Lê Quốc Thái | 2313097 |
| Đặng Gia Hưng | 2311318|
| Lê Sĩ Nhật Quang | 2312791|
| Đào Xuân Sơn | 2312954| 
This submission includes the implementation of two policies based on First-Fit and Best-Fit algorithms for solving the two-dimensional cutting-stock problem.
**First-Fit Policy:**
- The algorithm processes the product list sequentially.
- Each product is placed into the first stock where it fits, starting from the top-left corner of the stock and moving row by row.
- It also considers rotation of the product to maximize space utilization.
**Best-Fit Policy:**
- The algorithm evaluates all available stocks for each product and places the product in the stock that leaves the least unused area …
=> Resubmission_Group04_2312596_2313097_2311318_2312954 _2312791

student_submissions/s2312900_2310559_2420003_2312894_2312974/policy2312900_2310559_2420003_2312894_2312974.py, student_submissions/s2312900_2310559_2420003_2312894_2312974/requirements.txt
|  Name             | Student ID | Problem | 
| :---------------:|:------------:|:---------:|
| Phạm Duy Quý | 2312900 | Research First Fit Decreasing, write report| 
| Nguyễn Võ Đức Sơn | 2312974 | Rescreach First Fit Decreasing, source code implementation |
| Huỳnh Kim Quý | 2312894 | Research Simulated Annealing, source code implementation|
| Nguyễn Huy Hoàng | 2420003 | Research Simulated Annealing, source code implementation | 
| Nguyễn Phạm Mạnh Dũng | 2310559 | Case study, write report |
The First Fit Decreasing (FFD) algorithm is a greedy heuristic widely used for solving the 2D Cutting Stock Problem, where the goal is to minimize material waste when cutting smaller items from larger stock sheets. The algorithm begins by sorting the items in descending order based on their sizes …
=> 2312900_2310559_2420003_2312894_2312974 

student_submissions/s2352778_2353360_2352670_2352770_2352951/policy2352778_2353360_2352670_2352770_2352951.py, student_submissions/s2352778_2353360_2352670_2352770_2352951/requirements.txt
Group61:
1/ Nguyễn Nhật Nam - 2352778
2/Tô Nhã Vy - 2353360
3/Trần Gia Lâm - 2352670
4/Trần Hà My - 2352770
4/Lâm Thanh Phương - 2352951
Policy2352778_2353360_2352670_2352770_2352951: Genetic Algorithm and Column Generation for Cutting Stock Problem
This implementation introduces the Policy2210xxx class, which provides two strategies to solve the Cutting Stock Problem (CSP):
1. Policy 1 (GEN): A Genetic Algorithm (GA)-based solution designed to iteratively optimize stock utilization.
2. Policy 2 (COL): A Column Generation (CG) strategy that leverages Mixed-Integer Linear Programming (MILP) for precise solution refinement.
Features
Policy 1: Genetic Algorithm (GEN)
The Genetic Algorithm is tailored for scenarios requiring fast, approximate solutions. It employs:
• Initialization:
• …
=> Resubmission-Group 61: 2352778-2353360-2352951-2352770-2352670

student_submissions/s2213054_2213858_2210147_2212113/policy2213054_2213858_2210147_2212113.py
1. Lam Hoang Tan - 2213054 - _**Leader**_
2. Vo Quoc Tu - 2213858
3. Truong Nguyen Hoang Anh - 2210147
4. Nguyen Tran Khoa My - 2212113
**Column Generation (`policy_id = 1`)**
Column Generation is an optimization method used to solve large-scale cutting stock problems by iteratively generating new patterns to improve the solution. The algorithm starts by using a set of initial patterns and then solves a linear programming (LP) relaxation of the problem. In each iteration, it solves a pricing problem to generate new patterns that can potentially reduce waste and improve material utilization. By adding these new patterns to the model, the algorithm narrows down the feasible solutions, ultimately arriving at the optimal cutting pattern. Column Generation helps efficiently tackle problems …
=> Submission_2213054_2213858_2210147_2212113

student_submissions/s2352295_2352850_2352297_2352359/algorithm.py, student_submissions/s2352295_2352850_2352297_2352359/policy2352295_2352850_2352297_2352359.py, student_submissions/s2352295_2352850_2352297_2352359/requirements.txt
**Brief Description:**
This pull request contains the implementation of a policy solving the 2D Cutting Stock Problem by applying 2 heuristic methods: Bottom-Left (BL) Heuristic and First Fit Decreasing Height (FFDH) Heuristic:
- Bottom-Left Heuristic (policy_id=1): This is a heuristic method designed to solve the 2D Cutting Stock Problem, which includes effectively packing smaller rectangular items onto larger stock sheets, aiming to minimize the waste of material. By reordering the stock sheets and products in a reasonable rule, the algorithm follows a simple placement strategy to place the rectangular products so that the areas are optimized, minimizing the trim loss
- FFDH Heuristic (policy_id=2): Filling the stock sheets through the levels set by the heights of a certain number of …
=> Resubmission_Group_85_2352295_2352297_2352850_2352359

student_submissions/s2311064_2311188_2311454_2311888_2311409/policy2311064_2311188_2311454_2311888_2311409.py
Họ và tên|MSSV
:-:|:-:
Nguyễn Trần Đức Hoàng |2311064
Nguyễn Tấn Khang |2311454
Nguyễn Lâm Huy |2311188
Cao Vũ Hoàng Long |2311888
Đỗ Phú Khang |2311409
***Mô tả giải thuật***: Giải thuật suy nghiệm được thiết kế để giải bài toán cắt vật liệu hai chiều (2D CSP) bằng cách tối ưu hóa vị trí đặt các mảnh vật liệu nhỏ trên tấm nguyên liệu lớn. Mục tiêu là giảm thiểu không gian trống và đảm bảo tính hiệu quả trong việc sử dụng vật liệu. Thuật toán này sử dụng ba chiến lược chính: tối ưu hóa mật độ, giảm thiểu phân mảnh và tăng độ gọn của các vật liệu đã đặt.
- Hiệu quả trong việc tìm lời giải khả thi cho các bài toán lớn mà các thuật toán chính xác không thể giải trong thời gian hợp lý.
- Đơn giản trong triển khai và có khả năng áp dụng cho nhiều trường hợp thực tế với các ràng buộc phức tạp. …
=> Resubmission code group 119: 2311064_2311188_2311454_2311888_2311409

student_submissions/s2313180_2313079_2313133_2313053/policy2313180_2313079_2313133_2313053.py
Danh sách thành viên:
Huỳnh Võ Quốc Thắng - 2313180
Nguyễn Chí Thanh - 2313079
Nguyễn Văn Công Thành - 2313133
Nguyễn Chí Tân - 2313053
Thuật toán First-fit tối ưu hóa: Thuật toán First-Fit là một thuật toán heuristics đơn giản trong các bài toán cắt vật liệu hoặc đóng gói (Bin Packing). Trong bài toán tối ưu hóa, thuật toán First-Fit được dùng để tìm cách sử dụng tài nguyên một cách nhanh chóng và hiệu quả, dù không nhất thiết phải đạt kết quả tối ưu toàn cục.
Thuật toán di truyền: là một phương pháp tìm kiếm và tối ưu hóa dựa trên cơ chế tiến hóa tự nhiên của Charles Darwin. Thuật toán này mô phỏng các quá trình chọn lọc tự nhiên, đột biến, lai ghép và di truyền để tìm lời giải tối ưu hoặc gần tối ưu cho các bài toán phức tạp.
=> Resubmission_2313180_2313079_2313133_2313053

student_submissions/s2213140_2210830_2211384_2311712_2313612/policy2213140_2210830_2211384_2311712_2313612.py
- Nguyễn Thịnh Thành 2213140  
- Nguyễn Trường Giang 2210830
- Nguyễn Thiên Trí 2313612
- Vương Minh Khôi 2311712
- Tô Thế Hưng 2211384
First-Fit Decreasing Heurizstic (FFD) là một thuật toán heuristic phổ biến để giải quyết bài toán cutting stock và các bài toán đóng gói (packing problem). Thuật toán FFD đặc biệt hiệu quả trong các bài toán 2D cutting stock, nơi cần tối ưu hóa cách cắt các hình chữ nhật từ vật liệu để giảm thiểu lãng phí.  
FFD được xây dựng trên hai bước chính:  
- Sắp xếp giảm dần (Decreasing order):
- First-Fit (Lựa chọn khớp đầu tiên):  
FFD tận dụng ý tưởng ưu tiên các stock lớn trước và đặt hình vào các tấm sẵn có
để giảm số lượng tấm cần sử dụng. Điều này giúp:  
- Tối ưu hóa không gian: Các hình lớn được xử lý trước, tránh tình trạng các hình lớn không
thể được …
=> ReSubmission - Group 109 - 2213140_2210830_2211384_2311712_2313612

student_submissions/s2210xxx/policy2210xxx.py, student_submissions/s2311237_2252726_2012646_2420001_2311191/policy2311237_2252726_2012646_2420001_2311191.py
Group member IDs:
Phạm Quang Huy - 2311237
Trần Anh Tài - 2252726
Lê Xuân Bách - 2012646
Nguyễn Thái Giang - 2420001
Nguyễn Mạnh Huy - 2311191
Our submission consists of two heuristic algorithms:
- Best Fit: For every cut, the algorithm looks for the stock with the most cuts that it can fit. If such a stock is found, the cut will be placed on that stock; otherwise, the cut will be placed in a new stock. This process repeats until all the cuts are completed.
- Next Fit Decreasing Height: First, the algorithm sorts the cuts in descending order and selects a stock as the "current stock". It then places the first cut on this stock. For each subsequent cut, the algorithm will place it on the "current stock" until the stock can no longer fit the cut. At that point, the algorithm selects a new …
=> Resubmission - Group 153 - 2311237_2252726_2012646_2420001_2311191

student_submissions/s2311070_2310574_2310548_2310993/policy2311070_2310574_2310548_2310993.py, student_submissions/s2311070_2310574_2310548_2310993/requirements.txt
| Tên        | MSSV |
|-------------|-------------|
| Nguyễn Xuân Huy Hoàng | 2311070 |
| Trần Vĩnh Dũng | 2310574 |
| Bùi Trọng Hiển | 2310993 |
| Lê Quang Dũng | 2310548 |
- **Description**: This is a heuristic algorithm used for problems such as bin packing or cutting stock. In FFD, items are first sorted in decreasing order of size. Then, each item is placed into the first bin that has enough remaining space.
- **Advantages**: Simple to implement and provides a reasonably good approximation for many problems.
- **Applications**: Often used in manufacturing and logistics to minimize waste or optimize storage.
- **Description**: Actor-Critic is a reinforcement learning method that combines two components:
1. **Actor**: Responsible for selecting actions based on the policy.
2. …
=> Resubmission Group 126: 2311070_2310574_2310548_2310993

student_submissions/s2352704_2352814_2352564_2352691_2353140/policy2352704_2352814_2352564_2352691_2353140.py, student_submissions/s2352704_2352814_2352564_2352691_2353140/requirements.txt
**Team member Group 29**
Trần Hữu Hoàng Long (Leader) - 2352704 - Investigate 2D Cutting Stock Problem and organize team work
Nguyễn Nguyên Ngọc - 2352814 - Implement both policies based on team's document.
Lê Trần Đăng Khoa - 2352564 - Write the researched document.
Nguyễn Hoàng Long - 2352691 - Document codes and update team's document.
Nguyễn Đức Thịnh - 2353140 - Finalize everything and put it in LaTeX..
**Description of our team's policies**
Policy 1 (Largest Fit with Dynamic Sorting):
- Prioritizes placing largest products into stocks with the most remaining area.
- Dynamically adjusts sorting of stocks and products based on fit criteria, aiming to minimize stocks' usage and average waste.
Policy 2 (Column Generation):
- Uses a pattern-based approach to generate cutting patterns for …
=> Resubmission Group 29: 2352704_2352814_2352564_2352691_2353140
